### ISSUE TITLE
RFE: Kernal enhancement to detect and execute code in BONK space (Cartridge boot support)

### ISSUE THREAD

**Issue by mooinglemur** [X16Community/x16-rom#10]
David has expressed a need for Kernal support for the cartridge loader

I think we've settled on the idea for this. Kernal checks the contents of bank 32 (via a trampoline) to look for a signature.
$C000 = PETSCII "CX16" (cartridge signature)
$C004 = Kernal will jump here with interrupts disabled

**Comment by mooinglemur** [comment]
Closed by #12

**Comment by indigodarkwolf** [comment]
Merged! With great pleasure.
