### ISSUE TITLE
MONITOR clobbers 'free' ZP locations

### ISSUE THREAD

**Issue by tomxp411** [X16Community/x16-rom#111]
Forwarded from https://github.com/commanderx16/x16-rom/issues/329

> The machine code monitor clobbers a bunch of Zero page locations that are inside the "unused" area. 
> I would expect the monitor to not touch these. Or at least, backup on entry/ restore them on exit?
> https://github.com/commanderx16/x16-rom/blob/master/monitor/monitor.s#L105

My thinking is to nudge these variables up to the top of the empty space in ZP, maybe even overlap some of the BASIC zero page locations if we can do so without harm. We're talking about 12 bytes, so there has to be a buffer or something unused in BASIC while MONITOR is being used.

**Comment by stefan-b-jakobsson** [comment]
I'm not sure you can find a 12 byte buffer in low RAM that can be used for this purpose with no side effects.

It might be easier to place the backup in RAM bank #0 instead.

The segment BVARSB0 is a good candidate: 192 bytes are reserved for this segment but only 13 are currently used as far as I can tell.

We could shrink BVARSB0 a bit to make room for a new segment to be used by the monitor. What do you think?
