### ISSUE TITLE
I found a bug with the REN command.

### ISSUE THREAD

**Issue by bigjawed** [X16Community/x16-rom#117]
So, I was trying to program something, and that’s when I noticed something off with the REN command in X16 Basic.

Apparently if you type in a REN command, any value in RECT or FRAME that matches a line in the code will be affected.

For example:

10 RECT 0,0,10,10
REN 20,10

READY.
LIST

20 RECT 0,0,20,20

This should NOT happen. And this does not only affect the RECT command, but also the FRAME command as well. Please fix this.

**Comment by mooinglemur** [comment]
Renumber is supposed to affect these regular tokens

```
GOTO = $89
RUN  = $8a
RESTORE = $8c
GOSUB = $8d
THEN = $a7
```

But they're also improperly affecting these escaped tokens

```
FRAME = $ce $89
RECT = $ce $8a
MOUSE = $ce $8c
COLOR = $ce $8d
PSGWAV = $ce $a7
```
