### ISSUE TITLE
40/80 key always switches to VGA mode

### ISSUE THREAD

**Issue by jburks** [X16Community/x16-rom#145]
Hitting the 40/80 key will always change the video mode to VGA. Hitting the key again switches the font size but does not revert the video mode making this a one way function. In a recent case, the user thought their CRT had failed after mistakenly and unknowingly hitting the key while reaching for the backspace key on the official keyboard.

**Comment by mooinglemur** [comment]
The 40/80 key toggles the active NVRAM profile and applies it, including setting the output.

Would it make sense that the 40/80 key ignore the configured output?  Would it make sense to have output be de-coupled from the individual profiles and instead be stored a global in the nvram profile?

Would it also make sense to de-couple the keyboard layout from the two profiles and store that as a global?

**Comment by mooinglemur** [comment]
@jburks Do you have any input regarding the above? Having the display output tied to the profile slot will lead to this frustration, but do you think changing it would be an improvement?

**Comment by mooinglemur** [comment]
Please reopen or open a new issue if this is still a concern.
