### ISSUE TITLE
Screen $80 Console API Broken

### ISSUE THREAD

**Issue by gaekwad** [X16Community/x16-rom#152]
At some point, the console part of the GRAPH API for screen $80 mode broke.  You can see evidence of this with the "TEST1" and "TEST2" BASIC commands, which are behaving incorrectly.  I believe most of the code for this resides in "graphics/graph/console.s".

**Comment by stefan-b-jakobsson** [comment]
I tested it in R42 again, and it worked there. Something in R43 seems to have affected it.

**Comment by mooinglemur** [comment]
```
f4bcbab73d73791c69c5af4a7fae0f956b2e0afc is the first bad commit
commit f4bcbab73d73791c69c5af4a7fae0f956b2e0afc
Author: stefan-b-jakobsson <70063525+stefan-b-jakobsson@users.noreply.github.com>
Date:   Sun May 14 23:04:01 2023 +0300
```

That seems odd, but that's what bisect suggests.

**Comment by mooinglemur** [comment]
My previous comment was a red herring. It was new emulator behavior (randomized ram) that exposed this bug in the console routines.
