### ISSUE TITLE
MACPTR type kernal call for writing multiple bytes...

### ISSUE THREAD

**Issue by XarkLabs** [X16Community/x16-rom#165]
The SD card speed on X16 is nice (~100KB/sec), but saving is still 10x slower because it has to be done byte by byte still.  A nice feature would be a write call similar to the enhanced MACPTR read call, but able to save multiple bytes per call (MACPTR can do 1-512 bytes, so matching that would be nice).  Similar to MACPTR, it could indicate "not supported by device" so code can fall back to byte by byte.

**Comment by mooinglemur** [comment]
This was completed. The arguments mirror MACPTR, including carry flag, but a 0 in .A indicates 256 rather than up to 512.
