### ISSUE TITLE
MWHEEL not working

### ISSUE THREAD

**Issue by paulscottrobson** [X16Community/x16-rom#193]
On emulator - don't have real hardware ; print MX,MY,MB,MWHEEL in a loop in the emulator has MWHEEL fixed as 44 and MB is changin.

**Comment by mooinglemur** [comment]
Cannot reproduce:

![image](https://github.com/X16Community/x16-rom/assets/395186/fe0fcf6d-b238-4158-be45-227be63dbf2d)

Please ensure your Emulator build is sufficiently current.  Emulator support for passing the mouse wheel events through the emulated SMC appeared on 2023-09-24 in commit a5e89eea

**Comment by paulscottrobson** [comment]
My bad. I'd disabled calling make on my pull-rebuild makefile because at one point it wasn't building and forgotten it. I now get the results you do. I'm presuming MWHEEL is a delta ?

**Comment by mooinglemur** [comment]
It is a delta. IIRC, MWHEEL should return the accumulated delta since the previous call (up to the signed 8 bit limit). I'm on mobile at the moment so I'm going purely from memory, but I can confirm later.

**Comment by mooinglemur** [comment]
Yup, confirmed

```
:	clc			; Add movement to buffer
	adc wheel
	bvs :+			; Ignore if overflow
	sta wheel

**Comment by mooinglemur** [comment]
`
