### ISSUE TITLE
Caps lock causes ' to become shifted to "

### ISSUE THREAD

**Issue by mooinglemur** [X16Community/x16-rom#204]
at least in the ABC/X16 layout.

**Comment by stefan-b-jakobsson** [comment]
I think I have isolated this issue to the file keymap/klc/99409 ABC-Extended.klc, line 72:

```
28	OEM_7		4	0027	0022	-1	00e6	00c6		// APOSTROPHE, QUOTATION MARK, <none>, LATIN SMALL LETTER AE, LATIN CAPITAL LETTER AE
```

The 3rd column ("4") indicates that CAPS LOCK should affect this key.

We need to patch this klc file. I'm not yet familiar with the klcpatch file format that Mist made for this purpose.

**Comment by stefan-b-jakobsson** [comment]
I've been mocking around for some time with the script that builds the keymaps, klc_to_asm.py.

I'm sure it would be possible to make it fetch CAPS LOCK settings from klcpatch files, but it's a hassle. One thing is that klcpatch files seem to be used only in PETSCII mode.

Would you be OK if we simply edit the above mentioned line in 99409 ABC-Extended.klc?

I tested to select ABC Extended on my Mac. A single quote is outputted when CAPS LOCK is active.
