### ISSUE TITLE
Requirements for building have changed

### ISSUE THREAD

**Issue by JimmyDansbo** [X16Community/x16-rom#214]
For the last 2 or 3 releases, there has been a new requirement for building the kernal - **lzsa**
I suggest adding build/install instructions to the readme, just like there is for cc65.
In the meantime, going to https://github.com/emmanuel-marty/lzsa helped me get lzsa downloaded, compiled and installed

**Comment by irmen** [comment]
little addition: the makefile for lzsa mentions the 'clang' compiler explicitly. You can easily change that to gcc in the first line of their makefile, if you don't have clang but do have gcc

**Comment by mooinglemur** [comment]
The information was added in #192
