### ISSUE TITLE
In BASIC, commands DOS"8" and DOS"9" do not correctly switch device numbers.

### ISSUE THREAD

**Issue by DragWx** [X16Community/x16-rom#216]
I think I see why, too.

In bannex/dos.s, line 226:
```
	cmp #'8'
	beq dossw
	cmp #'9'
	beq dossw
```
then, line 304:
```
dossw	sta basic_fa
	rts
```
Unless I've misunderstood, this is actually storing the values $38 or $39 (i.e., the PETSCII values for the character '8' or the character '9') rather than the literal integer value of 8 or 9, which causes any further DOS commands to fail.

**Comment by mooinglemur** [comment]
Good catch, I think you're right.  Using numeric parameters works, but I think is quoted version was also meant to work.
