### ISSUE TITLE
Potential bug in cx16.GRAPH_draw_rect()

### ISSUE THREAD

**Issue by tallLeRoy** [X16Community/x16-rom#219]
I wrote a Prog8 program that rapidly draws filled rectangles on the screen. Most of the time, the rectangles draw in the position, size and color given in the parameters. Rarely, but reproducible, The kernel will draw the stroke of the rectangle too long in the vertical direction, then begin the fill color below the lower stroke. The horizontal size appears to be correct.

Here is the Prog8 program that will reproduce the bug.  mondrian.p8 

%import math
%import syslib
%import graphics
%zeropage basicsafe
%option no_sysinit

main {

    ubyte N    ; width of rect
    ubyte P    ; height of rect 
    ubyte Q    ; color of rect
    uword V    ; position of rect
    const ubyte A = 1

    sub start() {

        graphics.enable_bitmap_mode()
        graphics.clear_screen(1, 0)
        cx16.VERA_CTRL = 0               ; enable the BORDER register
        cx16.VERA_DC_BORDER = 0         ; border color black

        randomize()                         ; randomize N, P, Q, and V

        while true {
            if V + N > 2023 {
                V -= N
            }
            if V + (40 * P) > 2023 {
                V -= (40 * P) 
            }

            uword row = ((V + A) / 40) << 3
            uword col = ((V + A) % 40) << 3
            graphics.colors(0,Q)
            graphics.fillrect(col, row, N, P)

            randomize() ; lets have a new set of N, P, Q and V
        }
    }

    sub randomize() {
        N = ((math.rnd() % 10) + 1) << 3
        P = ((math.rnd() % 10) + 1) << 3
        Q = (math.rnd() % 15) + 1
        V = (math.rndw() % 1000)
        return
    }
} 

graphics.fillrect() is a Prog8 wrapper around cx16.GRAPH_draw_rect(). Same bug when calling cx16.GRAPH_draw_rect() directly.

May be an interrupt corrupting something during the draw.

**Comment by tallLeRoy** [comment]
<img width="1392" alt="Screenshot 2023-11-13 at 11 28 46 AM" src="https://github.com/X16Community/x16-rom/assets/12814167/deffa136-200d-49c2-9c5b-e3493e56a155">

The screenshot show the problem outlined in green. The black stroke of the box passes over the previous correctly drawn boxes. At the bottom of black stroke, we see a green box with no black stroke surrounding it.

**Comment by irmen** [comment]
I've added a `sys.set_irqd()` to disable all interrupts, to your code, and the problem still occurs. So it's not IRQ related.   
![image](https://github.com/X16Community/x16-rom/assets/1771820/6f710bf1-7e6c-44bd-b2b4-f563874bc49b)

**Comment by tallLeRoy** [comment]
Interesting, I wonder what it could be. No other threads running. And it is reliable almost all of the time. That one looks a little different in that the fill worked but the stroke did not.

**Comment by irmen** [comment]
Oh I think I see what the problem is, the program uses too large row values. Some rectangles extend outside the bottom of the screen. It seems the graph routine doesn't properly clip those.
If you change ` uword row = ((V + A) / 40) << 3` to ` uword row = ((V + A) / 50) << 3` the problem goes away.

**Comment by tallLeRoy** [comment]
added these two lines after row and col assignment
            if (row + P) > 239 P = lsb(239 - row)
            if (col + N) > 319 N = lsb(319 - col)
 
Still have an incomplete stroke like you have above.

**Comment by tallLeRoy** [comment]
![image](https://github.com/X16Community/x16-rom/assets/12814167/ba7a4967-ec86-43ee-9634-a3c345698c5a)

**Comment by tallLeRoy** [comment]
Just paused and saw two incomplete rects, top half of stroke missing. All rects are in bounds. Black border on all sides of the screen. Thinking that the incomplete stroke draw was caused by my pausing x16emu, I was surprised to see two incomplete at once.

**Comment by irmen** [comment]
They look to be in bounds, but actually weren't, in the original program as posted above. Once I changed that row variable to something small enough so that the rect actually fully fits inside the screen the problem vanished and all rectangles had a correct outline

I think your bounds change is still allowing the rectangles to overshoot.

**Comment by tallLeRoy** [comment]
Possibly, much more rare now with the clipping in my program. But I can still see some. Mode 03 is 320 x 240 right?

**Comment by irmen** [comment]
I tried your change which does actually has the right proportions, and it runs fine on my emulator now too. I wonder where you see that half-drawn rect now?  If you're pausing the emulator halfway through drawing a line, sure that would be the reason you see half drawn outlines on the screen. But if you let it run and inspect visually, everything is okay.
Try running the emulator with "-mhz 1" command line option to slow it down so you can see more easily what it draws.

**Comment by tallLeRoy** [comment]
here is a full screen with two errors
![image](https://github.com/X16Community/x16-rom/assets/12814167/84bc496f-2243-4b46-8182-0ada1476d624)

**Comment by irmen** [comment]
Ok hmm, now it's pixel counting then to try to reproduce the problem in 1 draw call of the rect routine.
Shouldn't bee too hard because it's a multiple of 8 or 10 I think that it uses

**Comment by tallLeRoy** [comment]
my loop looks like this now.

        while true {
;            if V + N > 2023 {
;               V -= N
;            }
;            if V + (40 * P) > 2023 {
;                V -= (40 * P) 
;            }
            uword row = (V / 40) << 3
            uword col = (V % 40) << 3
            if (row + P) > 239 P = lsb(239 - row)
            if (col + N) > 319 N = lsb(319 - col)
            graphics.colors(0,Q)
            sys.set_irqd()
            graphics.fillrect(col, row, N, P)
            sys.clear_irqd()

            randomize() ; lets have a new set of N, P, Q and V
        }

Still can have a paused screen with two unfinished boxes.

**Comment by irmen** [comment]
You'll probably have to figure out what the coordinates were that were passed to fillrect that drew the unfinished box.  Reduce the problem to a single call.

**Comment by tallLeRoy** [comment]
I modified the mondrian3.p8 program to allow one to record the origin, width and height of any rectangle on the screen. 
```
; mondrian5.p8
; this version will draw filled rectangles until the spacebar is pressed
; while the drawing in stopped use the mouse to highlight a top level
; rectangle of interest. The rectangle will be outlined in bright red 
; and the origin x, origin y, width and height will be output to the x16emu 
; console. Press the spacebar once more to resume drawing rectangles
%import math
%import syslib
%import graphics
%import emudbg
%import conv
%zeropage basicsafe
%option no_sysinit

main {

    ubyte N    ; width of rect
    ubyte P    ; height of rect 
    ubyte Q    ; color of rect
    uword V    ; position of rect
    const ubyte A = 1  
    bool   has_bounds = false


    sub start() {
        graphics.enable_bitmap_mode()
        graphics.clear_screen(1, 0)
        set_random_seeds()
        cx16.VERA_CTRL = 0                       ; enable the BORDER register  
        cx16.VERA_DC_BORDER = 0          ; border color black

        randomize()                         ; randomize N, P, Q, and V

        while true {
            uword row = (V / 40) << 3
            uword col = (V % 40) << 3
            if (row + P) > 240 P = lsb(240 - row)
            if (col + N) > 320 N = lsb(320 - col)
            graphics.colors(0,Q)
            graphics.fillrect(col, row, N, P)

            if cbm.GETIN() == ' ' {
                cx16.mouse_config(1, 336 >> 3, 256 >> 3)
                ubyte o_flags = 0   ; debounce the click
                do {
                    uword[2] @zp mouse_pos
                    ubyte flags = cx16.mouse_get(lsb(mouse_pos))
                    if flags != o_flags and flags & 1 {
                        report_rect(mouse_pos[0], mouse_pos[1])
                    }   
                    o_flags = flags                
                } until cbm.GETIN() == ' '
                cx16.mouse_config(0,0,0)
                has_bounds = false
            }

            randomize() ; lets have a new set of N, P, Q and V
        }
    }

    sub report_rect(uword pointer_x, uword pointer_y) {
        uword top = 0
        uword bottom = 0
        uword left = 0
        uword right = 0
        ubyte color = 0
        ubyte test_color
        word  delta = 0
        uword[4] bounds

        if has_bounds {
            graphics.colors(0, 1)
            graphics.rect(bounds[0], bounds[1], bounds[2], bounds[3])
        }

        cx16.FB_cursor_position(pointer_x, pointer_y)
        color = cx16.FB_get_pixel()

        ; find the top of the rect  
        delta = 0
        do {
            delta--
            cx16.FB_cursor_position(pointer_x, (pointer_y + delta)as uword)
            test_color = cx16.FB_get_pixel()
        } until test_color != color 
        top = pointer_y + delta

        ; find the bottom of the rect
        delta = 0
        do {
            delta++
            cx16.FB_cursor_position(pointer_x, (pointer_y + delta) as uword)
            test_color = cx16.FB_get_pixel()
        } until test_color != color 
        bottom = pointer_y + delta

        ; find the left of the rect
        delta = 0
        do {
            delta--
            cx16.FB_cursor_position((pointer_x + delta) as uword, pointer_y)
            test_color = cx16.FB_get_pixel()
        } until test_color != color 
        left = pointer_x + delta

        ; find the right of the rect
        delta = 0
        do {
            delta++
            cx16.FB_cursor_position((pointer_x + delta) as uword, pointer_y)
            test_color = cx16.FB_get_pixel()
        } until test_color != color 
        right = pointer_x + delta

        bounds[0] = left
        bounds[1] = top
        bounds[2] = right - left + 1    ; width
        bounds[3] = bottom - top + 1    ; height
        has_bounds = true

        graphics.colors($3b, color)
        graphics.rect(bounds[0], bounds[1], bounds[2], bounds[3])

        if emudbg.is_emulator() {
            emudbg.console_write( iso:"column " )
            conv.str_uw(bounds[0])
            emudbg.console_write( conv.string_out )
            emudbg.console_write( iso:" row " )
            conv.str_uw(bounds[1])
            emudbg.console_write( conv.string_out )
            emudbg.console_write( iso:" width " )
            conv.str_uw(bounds[2])
            emudbg.console_write( conv.string_out )
            emudbg.console_write( iso:" height " )
            conv.str_uw(bounds[3])
            emudbg.console_write( conv.string_out )
            emudbg.console_write( iso:" color " )
            conv.str_ub(color)
            emudbg.console_write( conv.string_out )
            emudbg.console_write( iso:" pixel color " ) 
            conv.str_ub(test_color)
            emudbg.console_write( conv.string_out )
            emudbg.console_write( iso:"\n" )
        }
    }

    sub randomize() {
        N = ((math.rnd() % 10) + 1) << 3
        P = ((math.rnd() % 10) + 1) << 3
        Q = (math.rnd() % 14) + 1  ; basic 15 colors - no black
;        Q = (math.rnd() % 254) + 1  ; expanded 254 colors - no black
        V = (math.rndw() % 1000)
        return
    }

    asmsub set_random_seeds() {
        %asm {{
            jsr cx16.entropy_get
            ; AY already contains the first seed
            stx cx16.r0L         ; R0 for the second seed    
            sty cx16.r0H
            jsr math.rndseed
        }}
    }
} 
```
After multiple runs of the program, I have yet to see a rectangle with incomplete surrounding lines when the program is stopped using the spacebar. 

This problem may be down to the interruption of the emulator to view the rectangles without new rectangles being drawn. My Mac M2 Pro Mini host may have something to do with it. There are multiple graphics processors in my Mac, it is possible that the emulator divides work drawing the boxes among them. So when the emulator is paused, multiple graphics thread are also stopped before completion. Irmen, please give this latest program a try and see if all of the rectangles you see after pressing the spacebar are complete. We may be able to close this issue if that is the case.

**Comment by tallLeRoy** [comment]
Interesting... mondrian5.p8 above has a cbm.GETIN() within the main draw rectangle loop. If I pause x16emu while that program is running. I do not see partially outlined boxes. Maybe cbm.GETIN() allows the emulator to clear its work before pausing.

**Comment by mooinglemur** [comment]
I see that there's been quite a bit of back and forth on this, but haven't had the focus to do a deep dive.  Is there anything I can help with or can you create a minimal test case that could show the wrong behavior?

**Comment by tallLeRoy** [comment]
Here is a minimum version of Mondrian6.p8 that produces the problem when x16emu is paused by selecting the menu.  When paused look for one or more filled rectangles with incomplete strokes around the bounds.

```
; mondrian6.p8
; minimum version

; run this program with x16emu
; while the program is running press either of the x16emu menu buttons
; on my Mac Mini, the x16emu stops until the menu is pressed again
; while stopped examine the top layers of filled rectangles. There may
; be one or more rectangles on screen where the black stroke around the 
; fill did not complete. 

%import math
%import syslib
%import graphics
%zeropage basicsafe
%option no_sysinit

main {

    ubyte N    ; width of rect
    ubyte P    ; height of rect 
    ubyte Q    ; color of rect
    uword V    ; position of rect

    sub start() {
        graphics.enable_bitmap_mode()
        graphics.clear_screen(1, 0)
        cx16.VERA_CTRL = 0                       ; enable the BORDER register  
        cx16.VERA_DC_BORDER = 0          ; border color black

        randomize()                         ; randomize N, P, Q, and V

        while true {
            uword row = (V / 40) << 3
            uword col = (V % 40) << 3
            if (row + P) > 240 P = lsb(240 - row)
            if (col + N) > 320 N = lsb(320 - col)
            graphics.colors(0,Q)
            graphics.fillrect(col, row, N, P)
           
            randomize() ; lets have a new set of N, P, Q and V
        }
    }

    sub randomize() {
        N = ((math.rnd() % 10) + 1) << 3
        P = ((math.rnd() % 10) + 1) << 3
        Q = (math.rnd() % 10) + 1  ; basic 15 colors - no black
        when Q {   ; brighten the darker colors, easier to see the stroke
            6 -> Q = 14
            11 -> Q = 15
        }
        V = (math.rndw() % 1000)
        return
    }
 } 
```

**Comment by irmen** [comment]
I really think this is an artifact of the screen refresh. Look what I just captured with a screenshot program.
No way this is actually drawn by the rectangle routine in vera's graphics memory, the screenshot is simply being taken while the window is refreshing its contents, I am guessing. Much like Vsync-tearing with moving screens

![image](https://github.com/X16Community/x16-rom/assets/1771820/e97a50f3-815c-4f65-9f6e-65b1c307b805)

**Comment by irmen** [comment]
@tallLeRoy what you could do to verify this is to not pause the emulator via some artificial external means like clicking on a menu button, but to program it into the code. For instance you could halt the drawing on a keypress/joystick button press, and resume it when released. I'm 99.99% certain you will not observe the apparently half-drawn rectangles if you do this.     I think this issue is a "non-issue".

**Comment by tallLeRoy** [comment]
I added a pause to mondrian6.p8    Whenever the left mouse button is down, the rectangle loop is paused waiting for the button release. When the rectangle draw loop is paused in this manner, all rectangles complete with the correct border. 

I believe that this bug is caused by pausing the emulator while it is drawing. So there is really nothing with GRAPH_draw_rect()

I am closing this issue
