### ISSUE TITLE
`clock_update` isn't exposed in the API

### ISSUE THREAD

**Issue by Yazwh0** [X16Community/x16-rom#229]
When overriding the kernel's IRQ, but want to use kernel functions it would be useful to be able to call all the functions that the kernel does in its handler. 

As `clock_update` isn't exposed, functionality around the jiffy count will not work.

If there is space in the api jump table then it would be useful to include this, otherwise some other set location?

**Comment by stefanoborini** [comment]
There seems to be space in the jump table part above $FF80. It seems that there are only 117 bytes used there, plus the MIST signature, of which I ignore the meaning at the moment.

But I wonder if a more flexible technique to perform system calls would be better. There's only so much you can do with a jump table in 256 bytes. Maybe it already exist?

**Comment by mooinglemur** [comment]
Wait, UDTIM is the C64 name for clock_update.  This call is already in the API.
