### ISSUE TITLE
Scratching a file with the same name as an existing directory, destroys that directory (on H/W, R46)

### ISSUE THREAD

**Issue by voidstar78** [X16Community/x16-rom#232]
NOTE the emulator does not appear to have this same behavior (the R45 emulator behaves as expected, when creating a file with same name as a folder it says FILE EXIST and no harm done)

On the HARDWARE with R46....
DOS"MD:BOB"
DOS"CD:BOB"
(make a file using edit or copy a file, etc, and/or make more sub-directories)
DOS"CD:/"  (back to root folder)
if you EDIT and try to save a file "BOB", X16EDIT seems to call out the error - which is expected/good behavior
however, if you do this:
10 PRINT"HELLO"
DOS"S:BOB"

CMDR-DOS seems to destroy the existing DIR called BOB and overwrite it with the file of the same name.   After the above sequence, I can no longer CD into BOB.   I didn't try any data-recovery or file-undelete kind of stuff to see if the folder contents might actually still exist -- this was just observed behavior (I didn't lose any actual data/files that I couldn't recover elsewhere).

I'd expect CMDR-DOS to behave in the "expected behavior" of not allowing the file to be saved to an existing directory name (and certainly not to destroy that directory and all its contents).

Again, observed only on R46 hardware.  Used two different SD cards.

**Comment by stefan-b-jakobsson** [comment]
I wasn't able to reproduce this either in the emulator with an SD card image or on hardware.

DOS"S:BOB" in the parent folder reports one file scratched even though there is none. That's a bit suspicious, but the directory is still there. I could also CD into the directory and open the file that I created.

**Comment by stefan-b-jakobsson** [comment]
Another issue is that it is possible to overwrite a directory by saving a file with the same name prepended by "@:". I don't think it's a good idea that you can do that.

**Comment by mooinglemur** [comment]
The overwrite bug has been fixed in #250
