### ISSUE TITLE
Default RED text mode color seems too dark

### ISSUE THREAD

**Issue by voidstar78** [X16Community/x16-rom#235]
After using text mode and real hardware for awhile - on both a flat panel LCD and Composite CRT - I was testing XINFO, and several times some people commented that they felt the stuff in RED color was hard to read.

So I looked into the default palette color for RED, and if it is at $FA05, then the default value appears to be 8.  I tried POKING to 10 and it seemed still too dark.   Using a value or 12 seemed more consistent with the other main colors (of the default color palette in text mode).    Proposing adjusting this value - existing games most likely load their own whole palette. 

Users concerned about this could also just update the AUTOBOOT.X16 to set the red.   Not sure what other ramifications there might be on this.  But my own interest is that text-mode reference guides (using XINFO .NFO) that make use of red could benefit from a slightly brighter default red  (15 is too bright, 12 felt about right).

**Comment by mooinglemur** [comment]
I'm very hesitant to change the default palette for several reasons, one of which is that by changing it, the VERA default palette and the X16 default palette would diverge.  The other is simply that the current palette is well-established and programs may have come to expect the palette that we have always had.

**Comment by voidstar78** [comment]
I'd agree, for all the same reasons.    It's just that after several "user reviews" (including David), we both commented how text in red was too hard to read (but also we're both old, ha!).   Note that's regard only to text mode.     One thought is that any software doing graphics is probably to load up their own palette?  That might ease one concern.   But my other thought is, if it is a big deal to any particular piece of software (or end user), it's easy enough to put a VPOKE in a launcher PRG of that program.    OTOH, readability is an important first impression, "legacy" programs can also VPOKE back (or "pre-launchers" to those PRGs).   Anyhow, just "for discussion" to have it on record.
