### ISSUE TITLE
`BVERIFY` returns `OK` on nearly everything

### ISSUE THREAD

**Issue by jestin** [X16Community/x16-rom#24]
The `BVERIFY` statement returns `OK` under pretty much every circumstance except when verifying ROM:

![image](https://user-images.githubusercontent.com/669174/219922515-d7294a62-8f28-4370-ae32-05ca2dee71c7.png)

This was run on the official emulator using an SD card.

When running on the official emulator using the host filesystem, it _never_ seemed to verify.

**Comment by mooinglemur** [comment]
Unable to reproduce w/ latest ROM/emu

![image](https://user-images.githubusercontent.com/395186/219973638-fc6ea10f-2944-46d0-abf5-b7ca2db3e33a.png)
![image](https://user-images.githubusercontent.com/395186/219973690-5bec6121-2020-4f16-8393-b597212f9747.png)

**Comment by jestin** [comment]
I mustn't have been running the latest.  I pulled the latest of both, rebuilt, and cannot reproduce my above results.  I'm going to close this issue.
