### ISSUE TITLE
-wuninit warnings from ROM bank $0A

### ISSUE THREAD

**Issue by indigodarkwolf** [X16Community/x16-rom#254]
Running x16emu with -wuninit, bank $0A now generates the following warnings:
```
Warning: 0A:C8E4 accessed uninitialized RAM address 01:ADFA
Warning: 0A:C659 accessed uninitialized RAM address 00:AE20
Warning: 0A:C659 accessed uninitialized RAM address 00:AE21
Warning: 0A:C659 accessed uninitialized RAM address 00:AE22
Warning: 0A:C659 accessed uninitialized RAM address 00:AE23
Warning: 0A:C659 accessed uninitialized RAM address 00:AE24
Warning: 0A:C659 accessed uninitialized RAM address 00:AE25
Warning: 0A:C659 accessed uninitialized RAM address 00:AE26
Warning: 0A:C659 accessed uninitialized RAM address 00:AE27
Warning: 0A:C913 accessed uninitialized RAM address 01:ADFA
```
Note that with x16emu's implementation (and Box16's), the warning is referring to the instruction after the one that has caused it. The offending instructions are actually located at 0A:C8E1 (`lda $ADFA`), 0A:C656 (`lda $AE00,x`), and 0A:C910 (`lda $ADFA`). 

No symbols for the code in this bank appear to be available or generated with the rom.bin. I'm not immediately sure where this executable code comes from, even, because it looks like the rom Makefile is assembling the rom.bin from smaller bin files that would amount to banks $00-$09, so there should be no ROM code in rom bank $A0... right? Evidently not, but it means I'm stopping here will let our rom experts investigate further, because I need to be returning to my day job.

Box16 will be patching its version of the -wuninit warning soonish to show correct addresses of the instructions that access uninitialized memory.

**Comment by irmen** [comment]
dump made with updated box16 to show the adjusted addresses

Warning: 0A:C8E1 accessed uninitialized RAM address 01:ADFA
Warning: 0A:C656 accessed uninitialized RAM address 00:AE20
Warning: 0A:C656 accessed uninitialized RAM address 00:AE21
Warning: 0A:C656 accessed uninitialized RAM address 00:AE22
Warning: 0A:C656 accessed uninitialized RAM address 00:AE23
Warning: 0A:C656 accessed uninitialized RAM address 00:AE24
Warning: 0A:C656 accessed uninitialized RAM address 00:AE25
Warning: 0A:C656 accessed uninitialized RAM address 00:AE26
Warning: 0A:C656 accessed uninitialized RAM address 00:AE27
Warning: 0A:C910 accessed uninitialized RAM address 01:ADFA

**Comment by indigodarkwolf** [comment]
There are a bunch of warnings before those, as well, but I'm assuming that those are intentional to probe the size of memory, or something.
