### ISSUE TITLE
Keyboard support for international layout is incomplete

### ISSUE THREAD

**Issue by ReallyNiceGuy** [X16Community/x16-rom#256]
The keyboard code uses IBM scancodes instead of PS2 scancodes directly.
This prevents the extended keys to be usable, like SLASH/QUESTION (scancode 0x73) in the pt-BR keyboard layout.

**Comment by stefan-b-jakobsson** [comment]
Could you take or link a photo of your keyboard layout so that we can understand what key this is.
Are 0x73 referring to a PS/2 set 1 scan code?

**Comment by ReallyNiceGuy** [comment]
The layout is as follows: [ABNT2](https://kbdlayout.info/kbdbr/scancodes+virtualkeys). Use the "ABNT" arrangement listed on this page.
Yes, 0x73 is the scancode on the PS/2, the key is named "ABNT C" and it is mapped to "slash".

**Comment by stefan-b-jakobsson** [comment]
I think I found it. I assume it is the key to the left of the right shift key. 

The 0x73 scan code is PS/2 set 1, not set 2 that is used by the SMC.

According to the translation table linked below, the set 1 scan code 0x73 is called "Keyboard Int'l 1" and it translates to set 2 scan code 0x51.

The IBM key codes are positional. The key code 0x38 is unused and matches the position of this key.

I've also looked at the code in keymap/klc_to_asm.py, that builds the key code tables used by the Kernal. There is a function that converts from PS/2 set 1 to set 2 called "ps2_set2_code_from_hid_code". As far as I can tell, it returns 0 if you give it the 0x73 scan code. If I'm not mistaken, this key on the pt-BR keyboard has never been working.

I will try to make a fix, adding support for the Keyboard Int'l 1 key.

[ https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjb2anoqM6EAxUfFhAIHWRsCCEQFnoECBYQAQ&url=https%3A%2F%2Fdownload.microsoft.com%2Fdownload%2F1%2F6%2F1%2F161ba512-40e2-4cc9-843a-923143f3456c%2Ftranslate.pdf&usg=AOvVaw0qYepWO28gAp8NbbWWs5EY&opi=89978449](url)

**Comment by stefan-b-jakobsson** [comment]
I've made a PR for the ROM and the emulator adding support for the slash/question mark key in the pt-BR layout. You can download it from the GitHub Actions if you want to test.

I have not yet updated the SMC. That will have to wait for another day.

**Comment by ReallyNiceGuy** [comment]
I downloaded the 'ROM Image.zip' from your PR and used on the "master" branch of x16-emulator. It didn't work.
When using '-log k', nothing gets printed when I press the corresponding 'slash' key.
Am I doing something wrong?

**Comment by stefan-b-jakobsson** [comment]
It's a bit hard for me to debug, as none of my keyboards have this key.
I made a temporary change to the emulator code in my PR that prints the key code as seen by the emulator to the terminal. Can you run this and report what value you get when pressing the slash key.

**Comment by ReallyNiceGuy** [comment]
Result of test: `key value: 135`

**Comment by stefan-b-jakobsson** [comment]
Great. I need to clean it up a bit, and then also implement the SMC side of things.
Do you have real hardware?

**Comment by ReallyNiceGuy** [comment]
Unfortunately I don't have the hardware.

**Comment by mooinglemur** [comment]
Closed by #278
