### ISSUE TITLE
There are no symbol files (.sym) for the X16Edit banks

### ISSUE THREAD

**Issue by Yazwh0** [X16Community/x16-rom#259]
Every other bank has a .sym file, which is copied to the Emulator.

**Comment by mooinglemur** [comment]
@stefan-b-jakobsson Can we get the outputs of x16-edit and basload such that the relist/symbolize/trace_lst scripts allow the source and symbols to appear in emulator traces?

**Comment by stefan-b-jakobsson** [comment]
I’ll have a look, but X16 Edit and Basload don’t currently export symbols (with the .export directive).

**Comment by stefan-b-jakobsson** [comment]
OK, I added the -g switch to the Makefile build targets. The change was just now pushed to X16edit master branch.

This will output all symbols, including local ones, to x16-edit/build/x16edit-rom.sym.

Is this good enough?

**Comment by mooinglemur** [comment]
Closed by #304
