### ISSUE TITLE
BASIC BANK command needs to be able to set ROM and RAM banks independently

### ISSUE THREAD

**Issue by mooinglemur** [X16Community/x16-rom#26]
Right now, BANK defaults to 0 and it applies to both ROM and RAM banks, and that is good for SYS commands, but bad for poking into $A000.

Also BASIC used to have the expectation that it started in RAM bank 1

Suggested syntax `BANK <ram>,<rom>`, `BANK <ram>`, and `BANK ,<rom>`

Also ROM bank is clamped to < 32, a restriction that needs to be lifted.

**Comment by stefan-b-jakobsson** [comment]
What typical use case are you thinking about, when you say that the current BANK statement is bad for poking?

**Comment by mooinglemur** [comment]
Because in the past, you would control what bank a POKE would reach in high ram by first poking ZP address 0. Now this has no effect and BANK takes precedence.

BANK defaults to 0, which is good for reaching the KERNAL via SYS.
but now because the BANK command affects RAM, too. The default RAM bank presented to BASIC is now 0.  This breaks compatibility with earlier expectations. And IMO it's a bad idea to expose the KERNAL's bank to BASIC by default when people have already had the expectation that access to $A000+ was by default in bank 1.

**Comment by stefan-b-jakobsson** [comment]
OK, I understand.

It's very bad practice, though, to interact with banked RAM or ROM without first explicitly select bank. No program can rely on the defaults to be selected when started.
