### ISSUE TITLE
Why does JSRFAR have this unique ABI?

### ISSUE THREAD

**Issue by stefanoborini** [X16Community/x16-rom#264]
I was checking jsrfar and I am a bit puzzled by the uniqueness of its ABI. All other kernal routines use real or pseudoregisters for inputs. JSRFAR seems to be the only one that uses PC+3 and PC+5 to pass the bank and location. This also means that it's the only routine whose arguments are given _after_ the call, and not before.

Why was it designed that way?

**Comment by stefanoborini** [comment]
Oh, I got it.

It's because otherwise you don't know how to pass the arguments to the _called_ routine.

**Comment by mooinglemur** [comment]
Yes, either it would need to have a preparatory routine to pass the called function and stage it somewhere, or done the way that it is.  jsrfar called routines can take args using all of the registers including flags.

PRIMM (a C128 API call) also has the argument after the call, but its implementation on the X16 only works if the ROM bank is set to 0 first.
