### ISSUE TITLE
Req. TILE(x,y) command to read back screen data

### ISSUE THREAD

**Issue by tomxp411** [X16Community/x16-rom#271]
From Discord:
> The 8-Bit Guy — Today at 6:40 PM
> I know we have the TILE command in BASIC.  Did we ever create the reverse of that?  I can't remember what it is, if we did.  Where you could do something like `A=TILE(x,y)`

This would read the character cell or tile index at row x, column y and return the character value or tile index. 

To simplify things, we Could limit the possible use cases for TILE() to the screen modes available with the SCREEN command.

I'm also going to suggest a partner `ATTR(x,y)` function, which returns the attribute byte from the next byte over.

**Comment by mooinglemur** [comment]
I'm pretty sure we cannot start the keyword with `TILE` as the tokenization appears to happen by searching statements first before functions, and the `TILE` statement will have precedence.  Any recommendations for the keyword name?

**Comment by tomxp411** [comment]
That would exclude anything starting with GET as well, then. Maybe CHRAT() or TILAT()

**Comment by mooinglemur** [comment]
Closed by #276
