### ISSUE TITLE
Req: memory var for cursor character in ISO/ANSI mode

### ISSUE THREAD

**Issue by tomxp411** [X16Community/x16-rom#299]
Add an address in low RAM that would allow for a configurable cursor character in ISO mode. 

So when using ISO mode with a custom character set, a user could POKE <cursor>,<char> to use a different character as the cursor. This would allow more flexible use of code pages, since the user could use any character in the character set as the blinking cursor character. 

The issue is that when writing a character set other than the ISO character set to VERA, the cursor ends up being a random glyph that is not the filled-box we know and love. For example, when using the new ANSI character set, the cursor turns into a [ƒ](https://www.ascii-code.com/character/%C6%92). 

Since different character sets put the filled block in a different place, (or often don't even have one!), having a programmable character for the blinking cursor would allow users to set whatever character they want as the cursor character. 

In the case of the ANSI/CP437 character set, it would be 219 or $DB, as would many other Code Pages. However, CP1040 (Korean PC Data Extended) doesn't even have a filled block, so CP1040 users would want to use something like ▓ ($14) or  ☼ ($0F)

Or, if the user is having a good day, maybe they want to poke $01 in there and have a 🙂.

**Comment by mooinglemur** [comment]
![image](https://github.com/X16Community/x16-rom/assets/395186/fadb4271-dad5-4faa-98c1-69697cf604f2)
![image](https://github.com/X16Community/x16-rom/assets/395186/7f17bd89-3e30-4642-91a5-48dec8462798)

**Comment by mooinglemur** [comment]
Docs added to https://github.com/X16Community/x16-docs/pull/170
