### ISSUE TITLE
Key repetition routine 

### ISSUE THREAD

**Issue by fredrikr** [X16Community/x16-rom#314]
It would be nice to have a ROM routine for turning key repetition on/off, and maybe read current status.

Turning on key repetition should be doable by sending command $f3 to the keyboard.

**Comment by djehuti** [comment]
My comment from that one:

>IIUC (from a Discord thread) the key repeat can be controlled by sending commands to the SMC.
It would be nice for the user to be able to adjust key repeat on/off, rate, etc., from the system without writing code.
>
>This could take the form of a BASIC extension command, or a system menu preference to go in nvram like the keyboard mapping (my favorite option), and/or a program that loads from disk but is distributed on the sd card.

If I get time, I'll try to contribute it.

**Comment by mooinglemur** [comment]
Closed via #316 
Docs via https://github.com/X16Community/x16-docs/pull/177

**Comment by mooinglemur** [comment]
Option is in the MENU, can be saved to NVRAM.  It isn't included in the AUTOBOOT.X16 export though.
