### ISSUE TITLE
Parameter Passing Space in DOS RAM Bank

### ISSUE THREAD

**Issue by tomxp411** [X16Community/x16-rom#34]
Reserve a small portion of RAM as a dedicated parameter-passing area. Ideally, this would be 1 page of memory. This page should be initialized to all zeros at boot time, and after that it will not require the KERNAL or BASIC support. 

The goal is to allow two programs to exchange parameters and return small amounts of data without resorting to drop files, the $400 space, or affecting banked memory. 

Using this space, we can formalize a parameter passing system that allows different programs to talk to each other. Rather than programs trying to stuff parameter data in random, unused places in memory, the programs can publish their own parameter specifications, and callers can use that spec to call these modular programs. 

For example, the system does not currently have a file picker API. But someone can write a universal file picker that accepts a starting path and returns the chosen file via the parameter space. Or a game that is too large to load in memory all at once can use overlays to handle different game stages, using the parameter space to control which stage is loaded. 

Requirements: 

* A small area of memory is reserved for user programs to talk to other user programs.
* The first byte of the parameter space is the length of the parameter data. A zero byte means "no parameters".
* Following bytes are parameter data. Applications decide the format for parameters they accept. 
* This space is initialized to zeros by the KERNAL.
* Programs are free to populate this as needed. Programs are _required_ to reset the first byte to zero at termination, if they are not passing parameters to another program. 

Additional thoughts / stretch goals:

* pseudo-variable or command/function to access this space from BASIC. Something like SETPARAM A$ to load the parameter page and A$=READPARAM() to read the parameter page. SETMARAM "" would clear it. 
* some way to LOAD and RUN a program and feed it parameters from immediate mode. maybe a SHELL command: `SHELL "PROGRAM","PARAMETERS"[,device]`

I'll work up the documentation for this. It's basically this, with some example use cases.

**Comment by mooinglemur** [comment]
I'm leaning toward reserving $BF00 and shifting things downward as needed.

**Comment by mooinglemur** [comment]
This choice would mainly be for safety, overrunning the buffer would usually land you in ROM space where writes have no consequence.

**Comment by tomxp411** [comment]
> overrunning the buffer would usually land you in ROM space where writes have no consequence.

That's probably the best reason I can think of for going that way.
