### ISSUE TITLE
Suggestion: RESET, POWEROFF, and other BASIC keywords for SMC control

### ISSUE THREAD

**Issue by tomxp411** [X16Community/x16-rom#36]
I discovered today that you can power the Commander off by sending a command to the SMC. (This is documented in the KERNAL guide.) 

As a convenience for users, I am suggesting some simple BASIC keywords to access this capability:

`POWEROFF`: Power off system: I2C $01/$00

`RESET`: triggers the Reset pin: I2C $02/$00

`REBOOT`: triggers the "hard reboot" (power cycle?) I2C $01/01

`ICWRITE <register>,<value>`: wrapper for the KERNAL i2c_write_byte function

`<data> = ICREAD(<register>)`: wrapper for i2c_read_byte function

I'm also considering example programs for the software collection. I have already added an assembly language RESET example to the KERNAL guide, in addition to the POWEROFF example that is already there.

**Comment by mooinglemur** [comment]
the `RESET` keyword already exists. It simply jumps through the ROM reset vector.

**Comment by mooinglemur** [comment]
Hard reboot currently does not work on real SMC, and there are comments in the code stating so.

**Comment by tomxp411** [comment]
Huh. That’s a bummer. That would have been a nice feature.

**Comment by mooinglemur** [comment]
> Huh. That’s a bummer. That would have been a nice feature.

Asserting the hardware reset line seems to be just as good in most cases.  That's what I ended up tying the REBOOT command to.

**Comment by tomxp411** [comment]
Well, I’m excited to get those features at all. Having I2C features in BASIC opens up a lot of possibilities.
