### ISSUE TITLE
[ENHANCEMENT] Import the DIRECTORY command from the TED machines.

### ISSUE THREAD

**Issue by calmsacibis995** [X16Community/x16-rom#360]
`LOAD"$"` overwrites the BASIC program in memory when called. It would be a convenience if the `DIRECTORY` command was ported from the Plus/4.

**Comment by irmen** [comment]
type this:

DOS"$

**Comment by mooinglemur** [comment]
You can also use `@$`

**Comment by calmsacibis995** [comment]
Oh, I get it now. Thanks for this information.
