### ISSUE TITLE
Memory map in the Native mode 65c816?

### ISSUE THREAD

**Issue by jsyk** [X16Community/x16-rom#368]
Since R47 the ROM detects 65c816. What is the memory map in the native mode? I.e. at which '816 BANKS are the CX16's low-mem, ram-banks and rom-banks, and I/O mapped?

**Comment by mooinglemur** [comment]
The memory map is exactly the same as on the 65C02.  Even with the '816, the X16 hardware operates only in the first 64K of address space as it does not decode the bank byte (the high 8 bits), so the benefits of the 65C816 processor are mainly the additional addressing modes and 16 bit operation.

Calling into the kernal can usually still be done in native mode, depending on the call, but mx=1 and DP=$0000 is required in any case.
