### ISSUE TITLE
improve entropy routine to also include other "randomness" sources

### ISSUE THREAD

**Issue by irmen** [X16Community/x16-rom#377]
Could the entropy_get() kernal routine be improved by including other sources of "randomness".
Currently it only reads from the VIA timer.

It could perhaps eor a byte of the result with the current scan line position, and maybe there are other bytes of semi randomness that we could include (PS2 data?   People use keys and move the mouse, is that usable from anywhere perhaps?)

**Comment by irmen** [comment]
A quick test program that plots the 3 bytes returned from the current entropy_get() routine (used as x, y and color) show heavy patterns in the results

![image](https://github.com/user-attachments/assets/8011bfb5-fe8c-41b5-a663-70b41a52e90a)

So even for seeding a RNG it's not ideal.

I propose the enhanced routine which produces this result:

![image](https://github.com/user-attachments/assets/6ee782cb-659f-4a42-8fba-6c079179b847)

I added the current scanline position into the mix and also tried to add a human factor to it by reading the last ps2 keyboard and mouse bytes (via extapi call)

The prog8 code for the proposed version is as follows

```
    asmsub entropy_get_improved() -> ubyte @A, ubyte @X, ubyte @Y {
        %asm {{
            lda #cx16.EXTAPI_ps2data_raw
            jsr cx16.extapi     ; add human into the mix: get last ps2 mouse in r0/r1 and key data in A
            eor cx16.via1t1h
            tax
            eor cx16.r0L
            adc cx16.via1t1l ; feed in .C from user
            tay
            eor cx16.r0H
            lda cx16.VERA_SCANLINE_L    ; add video scanline into the mix
            eor cx16.via1t1l
            rts
        }}
    }
```

Thoughts?   I'll convert it to a proper PR if this looks decent

**Comment by jkominek** [comment]
just a spectator, but, yow, that's hundreds of additional cycles. how's it look if you just add the scanline, and omit the i2c call?

**Comment by mooinglemur** [comment]
> just a spectator, but, ~yow, that's hundreds of additional cycles~. how's it look if you just add the scanline, and omit the i2c call?
> 
> edit: oops, no you're not calling the fetch, so it isn't expensive. sorry! still be curious about how it looks with just the scanline. you're not maintaining an entropy pool so the scanline is changing more often than that mouse data.

`ps2data_raw` contains the result of the last fetch from KERNAL memory.  This isn't terribly expensive as it doesn't do any i2c calls, and I think it's reasonable.

@irmen looks good to me.  .A remains the most entropic with your changes, which is best IMO.  Keep in mind when writing this for the KERNAL you don't need to go through extapi as you have direct access to the `ps2data_raw` sub as long as you `.import` it in `entropy.s`

**Comment by mooinglemur** [comment]
Though there is one pitfall with this.  `entropy_get` would now clobber r0 and r1 whereas in the past it did not.  Since it doesn't use r0/r1 for communication, it would be best if they were preserved and restored by `entropy_get`

**Comment by mooinglemur** [comment]
*OR*, probably much less hassle, you could implement the part of `ps2data_raw` you're interested in inside of `entropy_get`.   You can use the same KVARS macros that ps2data_raw uses to activate RAM bank 0.  `KVARS_END` restores the RAM bank without clobbering variables or flags.

**Comment by mooinglemur** [comment]
Though @jkominek does raise a point, at least indirectly.  The return from `ps2data_raw` only contains data whenever there has been mouse movement or a keystroke since the (default) IRQ handler ran.  The next `ps2data_fetch` zeros this data out, so it is unlikely you'll get data from it unless you get lucky, so it might not even be worth the cycles.

`keyd` faces a similar problem as it will likely be zero except when there are keystrokes in the buffer.

**Comment by irmen** [comment]
I assumed it would still contain the previous (non-zero) bytes from moving the mouse and/or hitting a key. Do I understand correctly then, that if you didn't touch anything after that anymore, the values returned after a scan, will be all zero?   Yes, than it is not useful at all to include those bytes.

**Comment by irmen** [comment]
Ok I've removed the PS2 stuff and only left the raster line in. The result is almost identical to the seemingly random noise from before, so it indeed seems not worth it to include the PS2 stuff.

````
            lda cx16.via1t1h
            tax
            adc cx16.via1t1l ; feed in .C from user
            tay
            lda cx16.VERA_SCANLINE_L    ; add video scanline into the mix
            eor cx16.via1t1l
            rts
```
