### ISSUE TITLE
Inefficient use of stack space on startup

### ISSUE THREAD

**Issue by Yazwh0** [X16Community/x16-rom#46]
`enter_basic` which is called after the kernel init, is a label in the kernel that in tern uses `jsfar` to get into the basic rom.

As this never returns the stack will always contain the overhead from this startup. It would be better for Basic to reset SP at entry so not 'waste' the 4 or so bytes that are otherwise left on the stack.

**Comment by Yazwh0** [comment]
There maybe more as I've not yet seen it return from any of these highlighted entries, but I dont know the Basic rom well enough to say for sure.

![image](https://user-images.githubusercontent.com/90315107/224407556-b3574fb4-afbb-4230-abb5-f705c086ae0e.png)

**Comment by mooinglemur** [comment]
Both cold and warm starts of BASIC reset the stack pointer to a specific value.  The fact that it's a jsrfar doesn't affect how this is done in BASIC.

I do not know why it's not reset to $(1)FF, but rather starts at a lower number.

At cold boot, the stack is initialized at `#stkend-256`, which resolves to `$FB`.  Any time BASIC itself resets the stack, it ends up at `#stkend-257` or `$FA`. I don't know if there are CBM legacies that depend on this, but I'm wary of touching these without a good reason.  I have no idea if anything depends on the contents of $1FB-$1FF.

**Comment by mooinglemur** [comment]
Mystery solved here.  CBM BASIC uses the highest part of the stack for temp storage!  $0200 is the location of the editor line buffer.  There are a few bytes before this that are used in a few places, one place is when typing in a program.  The line number is stored in this area during parsing.  Another is during processing of the INPUT statement.

Unfortunately this is not considered part of the stack in BASIC.
