### ISSUE TITLE
Change to lower case mode doesn't work reliably in R42

### ISSUE THREAD

**Issue by mobluse** [X16Community/x16-rom#48]
In the current web emulator (R42) on http://commanderx16.com/webemu/x16emu.html code of this type that change to lower case mode doesn't work if the system is stressed (but this code alone works):
```
10 CLR:GOTO 1010
1010 SCREEN $FF:COLOR 14,0:CLS
1090 PRINT "HELLO";:COLOR 7:PRINT CHR$($0E)
1100 PRINT "BYE"
```
but this works even if stressed
```
10 CLR:GOTO 1010
1010 SCREEN $FF:COLOR 14,0:CLS
1090 PRINT "HELLO":COLOR 7:PRINT CHR$($0E)
1100 PRINT "BYE"
```
I've included the full program that never works in the webemu. This worked before the upgrade to R42 of the web emulator and still works in the desktop emulator R42 on the same computer. It should change to lower case mode on line 1090, but this doesn't happen when that program is run after Reset, but if I insert a PRINT before it does work. You need to paste in this program and press the Reset button before you run it: 
[KEYWORDSABBR.txt](https://github.com/X16Community/x16-emulator/files/10942610/KEYWORDSABBR.txt)
"My browser / operating system: ChromeOS 13597.84.0, Chrome 109.0.0.0, No Flash version detected" according to https://scratch.mit.edu/, but in reality it is Debian Bullseye on Raspberry Pi 4 B running Chromium "Version 109.0.5414.112 (Official Build) Built on Raspbian , running on Debian 11 (32-bit)". My system is 64-bit, but the browser is 32-bit to enable DRM.

**Comment by mooinglemur** [comment]
I found what is happening.  The program prints an open quote here, which turns on quote mode.  There is no carriage return ($0D) before the attempted charset change that would exit quote mode.

![image](https://user-images.githubusercontent.com/395186/224441155-4ee49ab9-8a28-44e3-a289-b17a2899d35f.png)

Here's what happens in the simple case

![image](https://user-images.githubusercontent.com/395186/224441415-5e076584-d978-4dad-b805-e8e29e8187a8.png)

And here's your `$0E` being printed

![image](https://user-images.githubusercontent.com/395186/224441621-33cddf86-52ce-40e0-ad4a-7bea1cfdb8da.png)

**Comment by mooinglemur** [comment]
As for your "stress test" case in web emu, I have been unable to reproduce.  I haven't been able to get the short test to fail in web emu even under load.

**Comment by mobluse** [comment]
Thanks! Quote mode is the problem here, but there is a difference in the web emulator compared to the desktop emulator, but both are R42. The difference is that they don't use the exact same ROM. The ROM in the web emulator leads to that a double quote it output, but the desktop does not. My desktop R42 version is downloaded from the release page:
`-rw-r--r-- 1 pi pi 1098754 Mar  9 13:07 /home/pi/Downloads/x16emu_linux-aarch64-r42.zip`

It would be easier to test programs if the ROMs were the same. I could close this issue and open a new about that the ROMs should be the same in all R42 releases.

**Comment by Cyber-EX** [comment]
> Thanks! Quote mode is the problem here, but there is a difference in the web emulator compared to the desktop emulator, but both are R42. The difference is that they don't use the exact same ROM. The ROM in the web emulator leads to that a double quote it output, but the desktop does not. My desktop R42 version was downloaded from the release page: `-rw-r--r-- 1 pi pi 1098754 Mar 9 13:07 /home/pi/Downloads/x16emu_linux-aarch64-r42.zip`
> 
> It would be easier to test programs if the ROMs were the same. I could close this issue and open a new about that the ROMs should be identical in all R42 releases.

Please check now.

**Comment by mobluse** [comment]
Yes, it works now with the R42 ROM.
