### ISSUE TITLE
Empty Space in Rom is filled with 0xaa

### ISSUE THREAD

**Issue by Yazwh0** [X16Community/x16-rom#49]
0xaa is `tax`, so if an app arrives between 0xe918 and 0xfea7 (values are approximate ofc) execution will continue until 0xfea8 at which point a `brk` will occur.

It might be preferable to fill this with either `brk` or `stp` (0xdb) so execution stops immediately, giving a better chance to the developer to understand the problem given the PC will be correct.

**Comment by mooinglemur** [comment]
I would be strongly against `STP` as that would require a full CPU reset on a real 65C02. It wouldn't even respond to NMI.

I think there are reasons for choosing an alternating bit pattern as a fill value ($AA or $55), perhaps to stress the flashing process in a way that would cause the failure mode to be evident.  $AA has been the fill value for some time.
