### ISSUE TITLE
screen_default_color_from_nvram doesn't check Carry to detect an error

### ISSUE THREAD

**Issue by Yazwh0** [X16Community/x16-rom#51]
During the initialisation of the screen, after a call to `rtc_get_nvram`, the carry isn't checked for an error. if there is an issue this can lead to random values being used.

![image](https://user-images.githubusercontent.com/90315107/224511248-26565838-26b3-4dfe-8d4c-b0e32da415c2.png)
![image](https://user-images.githubusercontent.com/90315107/224511294-de046d0e-42b3-421b-84c4-b6584b9b1967.png)

**Comment by mooinglemur** [comment]
Fair point, but minimal risk.  If the random values come out don't checksum correctly or if they don't make sense for screen geometry, default values are used instead anyway.

**Comment by mooinglemur** [comment]
Never mind, these are isolated.  You're absolutely right.  BASIC also has a copy of this function that's similarly deficient.
