### ISSUE TITLE
Offset 6 of mouse cursor sprite gets reset when moved

### ISSUE THREAD

**Issue by tomxp411** [X16Community/x16-rom#71]
From [Java Cake Games](https://cx16forum.com/forum/memberlist.php?mode=viewprofile&u=3688) on the forums: 

The byte containing the collision mask, Z-depth, H-flip and V-flip gets reset to $0C whenever the mouse is moved. The offsets containing its address, mode, size and palette offset are not reset, so I don't see why that one needs to be.

This behaviour makes it awkward to write programs that make use of those properties. It feels like something that should only be set when the mouse is first enabled, which can then be changed.

Please see https://cx16forum.com/forum/viewtopic.php?t=6438 for more information.

**Comment by mooinglemur** [comment]
![image](https://user-images.githubusercontent.com/395186/227102405-ce04597f-392e-4c0a-8bb6-b0f0884cf36d.png)

**Comment by tomxp411** [comment]
https://user-images.githubusercontent.com/5290794/227120302-38477008-9c22-4dcc-8ed3-79076622840b.mp4
