### ISSUE TITLE
sym-files have duplicate names with different addresses

### ISSUE THREAD

**Issue by mobluse** [X16Community/x16-rom#81]
This is an update of https://github.com/commanderx16/x16-rom/issues/90 . This problem still exists for almost all sym files.

My idea was to generate a header file for cc65 with the contents of *.sym that is distributed with each binary release, but I discovered some symbols had different addresses using this command in Bash:
`sort audio.sym | uniq | sed -E '/@/d;s/^..........//' | sort | uniq -d`
The result is for ROM in R42:
```
.advance_voice
.done
.end
.error
.fail
.hz
.next
.noop
.no_retrigger
.noteloop
.panning
.playnote
.release
.rest
.skip_preserve
.skip_restore
.success
.volume
.wait
.write
```
This would lead to ambiguity about which address is the right. I believe it would be better if different addresses have different names.

The Bash command line that should generate the header file is:
`sort audio.sym | uniq | sed -E '/@/d;s/^al/#define /;s/ (......) \.(.+$)/ROMAUDIO_\2 (0x\1)/' > romaudio.h`

Then you could concatenate all h files generated from sym files or include all relevant h files.

Now you get a lot of errors due to different addresses:
```
$ cl65 -t cx16 -O -o eliza.prg eliza.c
../x16-emulator/rom.h(125): Error: Macro redefinition is not identical
../x16-emulator/rom.h(265): Error: Macro redefinition is not identical
../x16-emulator/rom.h(266): Error: Macro redefinition is not identical
../x16-emulator/rom.h(280): Error: Macro redefinition is not identical
../x16-emulator/rom.h(419): Error: Macro redefinition is not identical
../x16-emulator/rom.h(855): Error: Macro redefinition is not identical
../x16-emulator/rom.h(1794): Error: Macro redefinition is not identical
../x16-emulator/rom.h(1796): Error: Macro redefinition is not identical
../x16-emulator/rom.h(1852): Error: Macro redefinition is not identical
../x16-emulator/rom.h(1858): Error: Macro redefinition is not identical
../x16-emulator/rom.h(1975): Error: Macro redefinition is not identical
/home/pi/Downloads/cc65/include/cx16.h(208): Fatal: Too many errors
```

This would simplify new releases of cc65 for developing X16 C programs. Maybe you have some other way to produce h files for cc65 automatically.

**Comment by mooinglemur** [comment]
This is an unfortunate side effect of the lack of scopes in sym files.  I think it's a consequence of using `.proc` for scope and using ordinary labels inside that could clash with others.  I don't know what the best solution would be at this point.

**Comment by mooinglemur** [comment]
As of R43, all of the constants that are depended on by cc65 should be fairly well nailed down and should be current in cc65's repo, particularly for the ones that peek internal KERNAL memory.  Building C programs now should generally be forward-compatible with later ROM versions.

As any symbols that would be problematic for this GitHub issue are also ones that could have their address change in successive ROM releases, and since the current state suits building both ROM and emulator, I think solving this might be prohibitive considering the niche use case.

Feel free to reopen if you have other opinions. :)
