### ISSUE TITLE
VAL() Should Work for Hexadecimal Numbers

### ISSUE THREAD

**Issue by mobluse** [X16Community/x16-rom#82]
This old issue still exists in R42: https://github.com/commanderx16/x16-rom/issues/311

I think `VAL()` should work for hexadecimal numbers and not only for decimal as it does now.

`PRINT VAL("$FFFFFFF")`  
should print: `268435455`.

I believe it would not be too difficult to implement since the code already exists for converting numbers in code.

`PRINT $FFFFFFF`  
works now, and types: `268435455`.

Especially now when `HEX$()` exists. `HEX$()` converts without `$` as prefix, but I think that's OK since `$` could be added easily if one wants. It's also similar to how it works in other BASICs, e.g. GW-BASIC: http://www.antonis.de/qbebooks/gwbasman/hexs.html

In GW-BASIC `HEX$()` also works for negative numbers, e.g. `HEX$(-32768)` is `"8000"`, but negative numbers doesn't currently work with X16 BASIC `HEX$()`.

I don't think it's necessary to implement `VAL()` for binary numbers, even though `BIN$()` exists, but if one did they should probably have `%` as prefix, e.g. `%101`.

FreePascal uses the same prefixes:  
https://www.freepascal.org/docs-html/ref/refse6.html

**Comment by mooinglemur** [comment]
I believe the existing hex parser is doing pure integer math, while VAL leverages the floating point lib.  Unfortunately I don't think this would be a trivial change, but I'll leave it open as a request for enhancement.

**Comment by irmen** [comment]
sounds like the floating point value parsing routine has to be changed for this to work?  It would need to recognise a $ prefix (and arguably % as well for binary) and then make a small detour via the integer processing of those notations, and then converting that result into floating point itself again?

**Comment by mooinglemur** [comment]
I was mistaken about the scope of the work, but it did require studying the code a bit.
