### ISSUE TITLE
Can't build ROM on MacOs

### ISSUE THREAD

**Issue by stefan-b-jakobsson** [X16Community/x16-rom#86]
If you do changes to the ROM code, at least without committing them, you can no longer build the project on MacOS due to memory segment overflow.
The signature section becomes 18 characters, for instance like this:

```
-n -N 26ED9AB -n +
```

As only 16 characters are allowed, the build fails. You can of coarse increase the size of the signature section, but then the emulator fails to show the screen.

I can build the project if all changes are committed. Then the length of the signature is within the limit.

**Comment by mooinglemur** [comment]
Oof, that means that on your build system the `echo` command doesn't recognize `-n` as a switch and is outputting it literally.  Can you think of a more portable way?

**Comment by mooinglemur** [comment]
I had no idea it was doing this on Mac.  This is from the actions from the emulator build.  That `-n ` shouldn't be there.

`00000000   2D 6E 20 32  36 45 44 39  41 42 35 0A  00 00 00 00  -n 26ED9AB5.....`
